
def _prepare_price_prediction_input_correct(self, request) -> pd.DataFrame:
    """훈련된 모델과 동일한 특성으로 입력 데이터 전처리"""

    # 기본 숫자 특성들
    data = {
        'rating': request.rating,
        'review_count': request.review_count,
        'purchased_last_month': getattr(request, 'purchased_last_month', 0),  # 기본값 0
        'is_prime': getattr(request, 'is_prime', 0),  # 기본값 0
        'price_to_category_avg_ratio': request.price_to_category_avg_ratio,
        'price_to_keyword_avg_ratio': request.price_to_keyword_avg_ratio,
        'price_x_rating': request.rating * (request.price_to_category_avg_ratio * 50),  # 추정 가격
        'rating_x_review_count': request.rating * request.review_count,
        'price_x_review_count': (request.price_to_category_avg_ratio * 50) * request.review_count
    }

    # 모든 범주형 특성을 0으로 초기화

    data['category_디지털/가전 > 모니터'] = 0
    data['category_디지털/가전 > 음향가전 > 블루투스셋 > 블루투스이어폰/이어셋'] = 0
    data['category_디지털/가전 > 주변기기 > 마우스 > 무선마우스'] = 0
    data['category_디지털/가전 > 주변기기 > 마우스 > 유선마우스'] = 0
    data['category_디지털/가전 > 주변기기 > 마우스 > 프리젠터'] = 0
    data['category_디지털/가전 > 주변기기 > 키보드 > 무선키보드'] = 0
    data['category_디지털/가전 > 주변기기 > 키보드 > 유선키보드'] = 0
    data['category_생활/건강 > 주방용품 > 보관/밀폐용기 > 물병'] = 0
    data['category_스포츠/레저 > 캠핑 > 캠핑가구 > 캠핑의자'] = 0
    data['category_식품 > 음료 > 커피 > 원두/생두'] = 0
    data['brand_AULA'] = 0
    data['brand_Apple'] = 0
    data['brand_BOB'] = 0
    data['brand_CHERRY'] = 0
    data['brand_CMF'] = 0
    data['brand_COX'] = 0
    data['brand_DAREU'] = 0
    data['brand_FNR'] = 0
    data['brand_JBL'] = 0
    data['brand_KEEP'] = 0
    data['brand_KOMAX'] = 0
    data['brand_LG그램'] = 0
    data['brand_LG전자'] = 0
    data['brand_MSI'] = 0
    data['brand_NAVEE'] = 0
    data['brand_POLY'] = 0
    data['brand_QCY'] = 0
    data['brand_QSENN'] = 0
    data['brand_RAZER'] = 0
    data['brand_RNRN'] = 0
    data['brand_SPM'] = 0
    data['brand_Unknown'] = 0
    data['brand_갤럭시'] = 0
    data['brand_골든나인'] = 0
    data['brand_꼬미딜'] = 0
    data['brand_날진'] = 0
    data['brand_넘버엔'] = 0
    data['brand_네이처하이크'] = 0
    data['brand_노브랜드'] = 0
    data['brand_노스피크'] = 0
    data['brand_뉴웨스트커피'] = 0
    data['brand_다크브릭스'] = 0
    data['brand_더써드로스터스'] = 0
    data['brand_덕힙'] = 0
    data['brand_델몬트'] = 0
    data['brand_두유니드커피'] = 0
    data['brand_라바짜'] = 0
    data['brand_라익미'] = 0
    data['brand_락셀'] = 0
    data['brand_락앤락'] = 0
    data['brand_람주'] = 0
    data['brand_래빗커피'] = 0
    data['brand_레드빈'] = 0
    data['brand_레드코코'] = 0
    data['brand_레토'] = 0
    data['brand_로랜텍'] = 0
    data['brand_로이체'] = 0
    data['brand_로지텍'] = 0
    data['brand_로지텍G'] = 0
    data['brand_로티캠프'] = 0
    data['brand_루미낙'] = 0
    data['brand_루비아'] = 0
    data['brand_르모네'] = 0
    data['brand_릴팡'] = 0
    data['brand_마운트리버'] = 0
    data['brand_마추픽추'] = 0
    data['brand_매드독캠프'] = 0
    data['brand_맥스틸'] = 0
    data['brand_모모스커피'] = 0
    data['brand_몬테라'] = 0
    data['brand_바라던커피'] = 0
    data['brand_바워스앤윌킨스'] = 0
    data['brand_바이굿즈'] = 0
    data['brand_백당커피공장'] = 0
    data['brand_밴프'] = 0
    data['brand_버팔로'] = 0
    data['brand_베러베스트커피'] = 0
    data['brand_베이니크'] = 0
    data['brand_베이스어스'] = 0
    data['brand_벤큐'] = 0
    data['brand_본플래그'] = 0
    data['brand_볼티움'] = 0
    data['brand_뷰피니티'] = 0
    data['brand_브리즈문'] = 0
    data['brand_브리즈빈'] = 0
    data['brand_브리즈피크'] = 0
    data['brand_브리츠'] = 0
    data['brand_블라우풍트'] = 0
    data['brand_블랙빈스'] = 0
    data['brand_블랜더보틀'] = 0
    data['brand_삼대오백'] = 0
    data['brand_삼성'] = 0
    data['brand_샥즈'] = 0
    data['brand_센트팜'] = 0
    data['brand_소니'] = 0
    data['brand_수달리'] = 0
    data['brand_스노우피크'] = 0
    data['brand_스마트모니터'] = 0
    data['brand_스마트포인터'] = 0
    data['brand_스케이터'] = 0
    data['brand_스타벅스'] = 0
    data['brand_스텐락'] = 0
    data['brand_스피엘'] = 0
    data['brand_쏘빗'] = 0
    data['brand_아우라'] = 0
    data['brand_아이노트'] = 0
    data['brand_아이락스'] = 0
    data['brand_아이리버'] = 0
    data['brand_아임핏'] = 0
    data['brand_알래스카블랙'] = 0
    data['brand_알맹'] = 0
    data['brand_알파스캔'] = 0
    data['brand_앱코'] = 0
    data['brand_어쉐어'] = 0
    data['brand_에센티아팩토리'] = 0
    data['brand_에스메랄다'] = 0
    data['brand_엑스포인터'] = 0
    data['brand_엑토'] = 0
    data['brand_엠스톤'] = 0
    data['brand_엠지텍'] = 0
    data['brand_오니지'] = 0
    data['brand_오디세이'] = 0
    data['brand_오슬로'] = 0
    data['brand_오아'] = 0
    data['brand_와이드뷰'] = 0
    data['brand_울트라기어'] = 0
    data['brand_울트라와이드'] = 0
    data['brand_워너빈'] = 0
    data['brand_원두반점'] = 0
    data['brand_원스위크라이프'] = 0
    data['brand_유맥스'] = 0
    data['brand_인터픽셀'] = 0
    data['brand_일렉싱크'] = 0
    data['brand_일리'] = 0
    data['brand_일프로커피'] = 0
    data['brand_제뉴인'] = 0
    data['brand_제닉스크리에이티브'] = 0
    data['brand_제로웨이트'] = 0
    data['brand_젬스트'] = 0
    data['brand_주닷'] = 0
    data['brand_지오프리'] = 0
    data['brand_지클릭커'] = 0
    data['brand_지프'] = 0
    data['brand_카고컨테이너'] = 0
    data['brand_카나모'] = 0
    data['brand_카디움'] = 0
    data['brand_카멜'] = 0
    data['brand_카즈미'] = 0
    data['brand_캠프빌리지'] = 0
    data['brand_커세어'] = 0
    data['brand_커클랜드'] = 0
    data['brand_커피볶는집'] = 0
    data['brand_커피창고'] = 0
    data['brand_코누'] = 0
    data['brand_코베아'] = 0
    data['brand_코시'] = 0
    data['brand_콜맨'] = 0
    data['brand_콩볶는사람들'] = 0
    data['brand_콩스콩스'] = 0
    data['brand_쿠디'] = 0
    data['brand_쿠스포츠'] = 0
    data['brand_크로스오버'] = 0
    data['brand_키친아트'] = 0
    data['brand_키크론'] = 0
    data['brand_킹콩팩토리'] = 0
    data['brand_타파웨어'] = 0
    data['brand_테라로사'] = 0
    data['brand_토조'] = 0
    data['brand_트루버'] = 0
    data['brand_티버디'] = 0
    data['brand_펄사'] = 0
    data['brand_폴바셋'] = 0
    data['brand_프로쉐이커'] = 0
    data['brand_프리플로우'] = 0
    data['brand_플랜40'] = 0
    data['brand_피스넷'] = 0
    data['brand_필더컵'] = 0
    data['brand_필립스'] = 0
    data['brand_필립스모니터'] = 0
    data['brand_필립스오디오'] = 0
    data['brand_하루의시간'] = 0
    data['brand_한샘'] = 0
    data['brand_한성컴퓨터'] = 0
    data['brand_해커'] = 0
    data['brand_헤베커피'] = 0
    data['brand_헬리녹스'] = 0
    data['seller_2gn'] = 0
    data['seller_BONFLAG'] = 0
    data['seller_Besthall'] = 0
    data['seller_BreezeMoon'] = 0
    data['seller_CHERRY 체리키보드'] = 0
    data['seller_CUCERA'] = 0
    data['seller_DELESHOP'] = 0
    data['seller_FNR'] = 0
    data['seller_HKPHONE'] = 0
    data['seller_Helinox'] = 0
    data['seller_JVR'] = 0
    data['seller_LAKSELV'] = 0
    data['seller_LG전자인증점 DHCNC'] = 0
    data['seller_LG전자인증점 신영플러스'] = 0
    data['seller_LG전자인증점 지오비전'] = 0
    data['seller_MEGACOFFEE'] = 0
    data['seller_N정품 쇼핑몰'] = 0
    data['seller_O-ma'] = 0
    data['seller_SSG닷컴'] = 0
    data['seller_STORE벅스'] = 0
    data['seller_STORYLiNK'] = 0
    data['seller_Tiqui-Taca-BRO'] = 0
    data['seller_Titicaca'] = 0
    data['seller_Woods Coffee'] = 0
    data['seller_duckhip'] = 0
    data['seller_e파인드리빙'] = 0
    data['seller_illy store'] = 0
    data['seller_marketrush'] = 0
    data['seller_ono market'] = 0
    data['seller_spm'] = 0
    data['seller_가온인터내셔날'] = 0
    data['seller_간결커피로스터스'] = 0
    data['seller_감성캠핑 로고스'] = 0
    data['seller_고래커피'] = 0
    data['seller_골든나인'] = 0
    data['seller_그냥 커피'] = 0
    data['seller_그라도스커피'] = 0
    data['seller_그리니.'] = 0
    data['seller_김씨하우스'] = 0
    data['seller_꼬미딜'] = 0
    data['seller_낫싱 공식스토어'] = 0
    data['seller_네이버'] = 0
    data['seller_네이쳐플레이스'] = 0
    data['seller_뉴웨스트커피'] = 0
    data['seller_니드커피'] = 0
    data['seller_다다키친'] = 0
    data['seller_다얼유 게이밍샵'] = 0
    data['seller_다이아몬드그램'] = 0
    data['seller_다크브릭스'] = 0
    data['seller_댕댕이캠핑'] = 0
    data['seller_더써드로스터스'] = 0
    data['seller_더캠프빌리지'] = 0
    data['seller_덕주방'] = 0
    data['seller_드림팩토리샵'] = 0
    data['seller_디어다니'] = 0
    data['seller_디엘유통'] = 0
    data['seller_따봉몰.'] = 0
    data['seller_라가커피'] = 0
    data['seller_라이빙'] = 0
    data['seller_라인코 원두커피'] = 0
    data['seller_래빗커피'] = 0
    data['seller_레드코코-REDKOCO'] = 0
    data['seller_레스트빈'] = 0
    data['seller_로스터릭'] = 0
    data['seller_로스팅커피원두도매납품쇼핑몰'] = 0
    data['seller_로지텍공식스토어'] = 0
    data['seller_로지텍정품스토어'] = 0
    data['seller_로티몰닷컴'] = 0
    data['seller_루비아 커피'] = 0
    data['seller_르모네'] = 0
    data['seller_리 그'] = 0
    data['seller_리빙인저머니'] = 0
    data['seller_맘스캠핑'] = 0
    data['seller_매드독캠프'] = 0
    data['seller_맥스틸 공식스토어'] = 0
    data['seller_메이데이31'] = 0
    data['seller_모니터 전문 정품 판매점'] = 0
    data['seller_모닥불캠핑 거제점'] = 0
    data['seller_모르포'] = 0
    data['seller_모모스커피'] = 0
    data['seller_모사오카'] = 0
    data['seller_무드in하우스'] = 0
    data['seller_미니코코몰'] = 0
    data['seller_미스터송'] = 0
    data['seller_미티어소원'] = 0
    data['seller_바라던커피'] = 0
    data['seller_바이굿즈'] = 0
    data['seller_배드머슬러'] = 0
    data['seller_백당커피공장'] = 0
    data['seller_밴프'] = 0
    data['seller_버팔로 캠핑'] = 0
    data['seller_베러베스트'] = 0
    data['seller_베이니크샵'] = 0
    data['seller_보틀스'] = 0
    data['seller_볼티움'] = 0
    data['seller_브리즈피크'] = 0
    data['seller_브리츠 공식몰'] = 0
    data['seller_브리츠공식스토어'] = 0
    data['seller_블라우풍트'] = 0
    data['seller_블랙빈스 커피'] = 0
    data['seller_비욘드퍼니싱'] = 0
    data['seller_비트 박스'] = 0
    data['seller_빈마켓'] = 0
    data['seller_빈스메이드'] = 0
    data['seller_살림의 힘'] = 0
    data['seller_삼대오백 스토어'] = 0
    data['seller_삼성JBL온라인스토어'] = 0
    data['seller_삼성공식파트너 엠디텍'] = 0
    data['seller_삼성공식파트너 엠디텍PC'] = 0
    data['seller_삼성공식파트너 오제앤에스'] = 0
    data['seller_삼성공식파트너 제이유'] = 0
    data['seller_삼성공식파트너사 포디아이'] = 0
    data['seller_삼성스마트쇼핑스토어'] = 0
    data['seller_삼성인증모니터파트너'] = 0
    data['seller_샥즈 코리아'] = 0
    data['seller_서원리빙'] = 0
    data['seller_설빈'] = 0
    data['seller_성정마트'] = 0
    data['seller_세네카 커피'] = 0
    data['seller_센트팜'] = 0
    data['seller_솔루딕캠핑'] = 0
    data['seller_송마리커피집'] = 0
    data['seller_쇼핑 Pay'] = 0
    data['seller_수달리커피'] = 0
    data['seller_쉐이크스피어'] = 0
    data['seller_스노우커피'] = 0
    data['seller_스마트 Inc'] = 0
    data['seller_스윗소다'] = 0
    data['seller_시골커피'] = 0
    data['seller_쏘빗 공식몰'] = 0
    data['seller_아이덴티티커피랩'] = 0
    data['seller_아이리버 공식대리점 샤후후'] = 0
    data['seller_아이리버스토어'] = 0
    data['seller_아이언빅'] = 0
    data['seller_아임핏'] = 0
    data['seller_알맹키즈'] = 0
    data['seller_액티브라이프'] = 0
    data['seller_어쉐어'] = 0
    data['seller_얼리텍'] = 0
    data['seller_에디샵 공식판매점'] = 0
    data['seller_에센티아 팩토리'] = 0
    data['seller_에이디바이크'] = 0
    data['seller_오늘새로'] = 0
    data['seller_오니지'] = 0
    data['seller_오렌지스펙트럼'] = 0
    data['seller_올댓픽'] = 0
    data['seller_와이드뷰'] = 0
    data['seller_와이엘사이언스'] = 0
    data['seller_와이제이바스켓'] = 0
    data['seller_와이피게이밍기어'] = 0
    data['seller_왕도매 아울렛'] = 0
    data['seller_워너빈 커피'] = 0
    data['seller_원당커피공장'] = 0
    data['seller_원두반점'] = 0
    data['seller_원두천국'] = 0
    data['seller_원스위크라이프'] = 0
    data['seller_위즈플래닛'] = 0
    data['seller_유로키친'] = 0
    data['seller_유리카트'] = 0
    data['seller_이너프812'] = 0
    data['seller_이든리빙'] = 0
    data['seller_이리디아'] = 0
    data['seller_이수팩토리로스터즈'] = 0
    data['seller_인디에이'] = 0
    data['seller_일등대한민국'] = 0
    data['seller_일리천국'] = 0
    data['seller_일프로커피'] = 0
    data['seller_잇츠레저'] = 0
    data['seller_제뉴인커피'] = 0
    data['seller_제로웨이트'] = 0
    data['seller_지포모아'] = 0
    data['seller_직구플리즈'] = 0
    data['seller_캐주얼캠핑'] = 0
    data['seller_캠핑레시피'] = 0
    data['seller_캠핑멀티샵'] = 0
    data['seller_캠핑토크'] = 0
    data['seller_커스텀 커피 마켓'] = 0
    data['seller_커피마켓어스'] = 0
    data['seller_커피볶는집'] = 0
    data['seller_커피창고'] = 0
    data['seller_커피포레스트'] = 0
    data['seller_케이트마켓'] = 0
    data['seller_코스트코이케아'] = 0
    data['seller_코시'] = 0
    data['seller_코코로운'] = 0
    data['seller_코코장수몰'] = 0
    data['seller_콩볶는사람들'] = 0
    data['seller_콩스콩스'] = 0
    data['seller_쿠스포츠'] = 0
    data['seller_쿠팡'] = 0
    data['seller_쿡샵'] = 0
    data['seller_퀘스트빈'] = 0
    data['seller_키크론 공식스토어'] = 0
    data['seller_킹콩팩토리.'] = 0
    data['seller_탑 플레이스'] = 0
    data['seller_티에스shop'] = 0
    data['seller_티타임커피'] = 0
    data['seller_팔공티앤씨'] = 0
    data['seller_펀키스'] = 0
    data['seller_포랩스커피컴퍼니'] = 0
    data['seller_포올'] = 0
    data['seller_프라이스킬'] = 0
    data['seller_프라이티마켓'] = 0
    data['seller_프리플로우'] = 0
    data['seller_플랜포티'] = 0
    data['seller_플롬아웃도어 울산점'] = 0
    data['seller_피쉬앤카'] = 0
    data['seller_피에스퍼니싱'] = 0
    data['seller_필더컵'] = 0
    data['seller_필로비'] = 0
    data['seller_하루의 시간'] = 0
    data['seller_한성컴퓨터'] = 0
    data['seller_헤베커피'] = 0
    data['seller_헬로우캠핑'] = 0
    data['seller_헬린이상점'] = 0
    data['seller_헬킹콩'] = 0
    data['seller_홈니크'] = 0
    data['search_keyword_마우스'] = 0
    data['search_keyword_모니터'] = 0
    data['search_keyword_물통'] = 0
    data['search_keyword_블루투스 이어폰'] = 0
    data['search_keyword_캠핑 의자'] = 0
    data['search_keyword_커피 원두'] = 0
    data['search_keyword_키보드'] = 0
    data['maker_AKT'] = 0
    data['maker_AULA'] = 0
    data['maker_Apple'] = 0
    data['maker_BOB'] = 0
    data['maker_CHERRY'] = 0
    data['maker_COX'] = 0
    data['maker_FLESPORTS'] = 0
    data['maker_KOMAX'] = 0
    data['maker_LG전자'] = 0
    data['maker_MSI'] = 0
    data['maker_QCY'] = 0
    data['maker_QSENN'] = 0
    data['maker_RAZER'] = 0
    data['maker_SPM'] = 0
    data['maker_TOGRAN'] = 0
    data['maker_Unknown'] = 0
    data['maker_간결커피로스터스'] = 0
    data['maker_날진'] = 0
    data['maker_네이처하이크'] = 0
    data['maker_뉴웨스트커피'] = 0
    data['maker_다얼유'] = 0
    data['maker_다크브릭스'] = 0
    data['maker_더써드로스터스'] = 0
    data['maker_라바짜'] = 0
    data['maker_라익미'] = 0
    data['maker_라인코'] = 0
    data['maker_락앤락'] = 0
    data['maker_레드빈'] = 0
    data['maker_레토'] = 0
    data['maker_레토지엠에스'] = 0
    data['maker_로랜텍'] = 0
    data['maker_로이체'] = 0
    data['maker_로지레스'] = 0
    data['maker_로지텍'] = 0
    data['maker_로티'] = 0
    data['maker_릴팡'] = 0
    data['maker_마당발'] = 0
    data['maker_마추픽추'] = 0
    data['maker_맥스틸'] = 0
    data['maker_몽돌'] = 0
    data['maker_바라던커피'] = 0
    data['maker_바워스앤윌킨스'] = 0
    data['maker_백당커피공장'] = 0
    data['maker_베러베스트커피'] = 0
    data['maker_베이스어스'] = 0
    data['maker_벤큐'] = 0
    data['maker_보틀스'] = 0
    data['maker_브리즈문'] = 0
    data['maker_브리츠'] = 0
    data['maker_블라우풍트'] = 0
    data['maker_블랙빈스'] = 0
    data['maker_비니시클'] = 0
    data['maker_비에프엘'] = 0
    data['maker_삼성전자'] = 0
    data['maker_삼지아이티'] = 0
    data['maker_소니'] = 0
    data['maker_스노우피크'] = 0
    data['maker_스케이터'] = 0
    data['maker_스타벅스'] = 0
    data['maker_스피엘'] = 0
    data['maker_아로마빌커피'] = 0
    data['maker_아이락스'] = 0
    data['maker_아이리버'] = 0
    data['maker_아이에이커머스'] = 0
    data['maker_알맹'] = 0
    data['maker_알파스캔'] = 0
    data['maker_앱코'] = 0
    data['maker_에센티아팩토리'] = 0
    data['maker_에스앤제이스토어'] = 0
    data['maker_에이플러스엑스'] = 0
    data['maker_엑토'] = 0
    data['maker_엠스톤글로벌'] = 0
    data['maker_엠엔지이'] = 0
    data['maker_엠지텍'] = 0
    data['maker_오니지'] = 0
    data['maker_오아'] = 0
    data['maker_우드인터내셔날'] = 0
    data['maker_워너빈로스터리'] = 0
    data['maker_유맥스'] = 0
    data['maker_익스프레스럭코리아'] = 0
    data['maker_인터픽셀'] = 0
    data['maker_일디오'] = 0
    data['maker_일렉싱크'] = 0
    data['maker_일리'] = 0
    data['maker_일프로커피컴퍼니'] = 0
    data['maker_제뉴인'] = 0
    data['maker_제닉스크리에이티브'] = 0
    data['maker_젬스트'] = 0
    data['maker_주닷'] = 0
    data['maker_지오라인'] = 0
    data['maker_지클릭커'] = 0
    data['maker_지프'] = 0
    data['maker_청연엠엔에스'] = 0
    data['maker_초이스테크놀로지'] = 0
    data['maker_카고컨테이너'] = 0
    data['maker_카라신'] = 0
    data['maker_카멜'] = 0
    data['maker_카즈미'] = 0
    data['maker_커세어'] = 0
    data['maker_커피디오리진'] = 0
    data['maker_커피마켓어스'] = 0
    data['maker_커피포레스트'] = 0
    data['maker_코뉴'] = 0
    data['maker_코베아'] = 0
    data['maker_코스트코'] = 0
    data['maker_콜맨'] = 0
    data['maker_콩볶는사람들'] = 0
    data['maker_콩스콩스'] = 0
    data['maker_쿠디'] = 0
    data['maker_쿠스포츠'] = 0
    data['maker_크로스오버존'] = 0
    data['maker_키친아트'] = 0
    data['maker_키크론'] = 0
    data['maker_타파웨어'] = 0
    data['maker_토조'] = 0
    data['maker_트래딧'] = 0
    data['maker_트루버'] = 0
    data['maker_티타임'] = 0
    data['maker_팔공티앤씨'] = 0
    data['maker_포유아이엔씨'] = 0
    data['maker_퓨전에프앤씨'] = 0
    data['maker_프리플로우'] = 0
    data['maker_플랜40'] = 0
    data['maker_플랜트로닉스'] = 0
    data['maker_필립스'] = 0
    data['maker_하이비프리'] = 0
    data['maker_한샘'] = 0
    data['maker_한성컴퓨터'] = 0
    data['maker_헬리녹스'] = 0
    data['naver_category1_디지털/가전'] = 0
    data['naver_category1_생활/건강'] = 0
    data['naver_category1_스포츠/레저'] = 0
    data['naver_category1_식품'] = 0
    data['naver_category2_모니터'] = 0
    data['naver_category2_음료'] = 0
    data['naver_category2_음향가전'] = 0
    data['naver_category2_주방용품'] = 0
    data['naver_category2_주변기기'] = 0
    data['naver_category2_캠핑'] = 0
    data['naver_category3_nan'] = 0
    data['naver_category3_마우스'] = 0
    data['naver_category3_보관/밀폐용기'] = 0
    data['naver_category3_블루투스셋'] = 0
    data['naver_category3_캠핑가구'] = 0
    data['naver_category3_커피'] = 0
    data['naver_category3_키보드'] = 0
    data['naver_category4_nan'] = 0
    data['naver_category4_무선마우스'] = 0
    data['naver_category4_무선키보드'] = 0
    data['naver_category4_물병'] = 0
    data['naver_category4_블루투스이어폰/이어셋'] = 0
    data['naver_category4_원두/생두'] = 0
    data['naver_category4_유선마우스'] = 0
    data['naver_category4_유선키보드'] = 0
    data['naver_category4_캠핑의자'] = 0
    data['naver_category4_프리젠터'] = 0

    # 실제 값에 따라 해당 특성을 1로 설정
    # category 처리 (정확한 매핑 필요)
    category_value = getattr(request, 'category', 'Unknown')
    category_mapping = ['디지털/가전 > 모니터', '디지털/가전 > 음향가전 > 블루투스셋 > 블루투스이어폰/이어셋', '디지털/가전 > 주변기기 > 마우스 > 무선마우스', '디지털/가전 > 주변기기 > 마우스 > 유선마우스', '디지털/가전 > 주변기기 > 마우스 > 프리젠터', '디지털/가전 > 주변기기 > 키보드 > 무선키보드', '디지털/가전 > 주변기기 > 키보드 > 유선키보드', '생활/건강 > 주방용품 > 보관/밀폐용기 > 물병', '스포츠/레저 > 캠핑 > 캠핑가구 > 캠핑의자', '식품 > 음료 > 커피 > 원두/생두']
    if category_value in category_mapping:
        data[f'category_{category_value}'] = 1
    elif category_mapping:  # 기본값으로 첫 번째 값 사용
        data[f'category_{category_mapping[0]}'] = 1

    # brand 처리
    brand_value = getattr(request, 'brand', 'Unknown')
    brand_mapping = ['AULA', 'Apple', 'BOB', 'CHERRY', 'CMF', 'COX', 'DAREU', 'FNR', 'JBL', 'KEEP', 'KOMAX', 'LG그램', 'LG전자', 'MSI', 'NAVEE', 'POLY', 'QCY', 'QSENN', 'RAZER', 'RNRN', 'SPM', 'Unknown', '갤럭시', '골든나인', '꼬미딜', '날진', '넘버엔', '네이처하이크', '노브랜드', '노스피크', '뉴웨스트커피', '다크브릭스', '더써드로스터스', '덕힙', '델몬트', '두유니드커피', '라바짜', '라익미', '락셀', '락앤락', '람주', '래빗커피', '레드빈', '레드코코', '레토', '로랜텍', '로이체', '로지텍', '로지텍G', '로티캠프', '루미낙', '루비아', '르모네', '릴팡', '마운트리버', '마추픽추', '매드독캠프', '맥스틸', '모모스커피', '몬테라', '바라던커피', '바워스앤윌킨스', '바이굿즈', '백당커피공장', '밴프', '버팔로', '베러베스트커피', '베이니크', '베이스어스', '벤큐', '본플래그', '볼티움', '뷰피니티', '브리즈문', '브리즈빈', '브리즈피크', '브리츠', '블라우풍트', '블랙빈스', '블랜더보틀', '삼대오백', '삼성', '샥즈', '센트팜', '소니', '수달리', '스노우피크', '스마트모니터', '스마트포인터', '스케이터', '스타벅스', '스텐락', '스피엘', '쏘빗', '아우라', '아이노트', '아이락스', '아이리버', '아임핏', '알래스카블랙', '알맹', '알파스캔', '앱코', '어쉐어', '에센티아팩토리', '에스메랄다', '엑스포인터', '엑토', '엠스톤', '엠지텍', '오니지', '오디세이', '오슬로', '오아', '와이드뷰', '울트라기어', '울트라와이드', '워너빈', '원두반점', '원스위크라이프', '유맥스', '인터픽셀', '일렉싱크', '일리', '일프로커피', '제뉴인', '제닉스크리에이티브', '제로웨이트', '젬스트', '주닷', '지오프리', '지클릭커', '지프', '카고컨테이너', '카나모', '카디움', '카멜', '카즈미', '캠프빌리지', '커세어', '커클랜드', '커피볶는집', '커피창고', '코누', '코베아', '코시', '콜맨', '콩볶는사람들', '콩스콩스', '쿠디', '쿠스포츠', '크로스오버', '키친아트', '키크론', '킹콩팩토리', '타파웨어', '테라로사', '토조', '트루버', '티버디', '펄사', '폴바셋', '프로쉐이커', '프리플로우', '플랜40', '피스넷', '필더컵', '필립스', '필립스모니터', '필립스오디오', '하루의시간', '한샘', '한성컴퓨터', '해커', '헤베커피', '헬리녹스']
    if brand_value in brand_mapping:
        data[f'brand_{brand_value}'] = 1
    elif 'Unknown' in brand_mapping:
        data['brand_Unknown'] = 1
    elif brand_mapping:  # 기본값으로 첫 번째 값 사용
        data[f'brand_{brand_mapping[0]}'] = 1

    # seller 처리
    seller_value = getattr(request, 'seller', 'Unknown')
    seller_mapping = ['2gn', 'BONFLAG', 'Besthall', 'BreezeMoon', 'CHERRY 체리키보드', 'CUCERA', 'DELESHOP', 'FNR', 'HKPHONE', 'Helinox', 'JVR', 'LAKSELV', 'LG전자인증점 DHCNC', 'LG전자인증점 신영플러스', 'LG전자인증점 지오비전', 'MEGACOFFEE', 'N정품 쇼핑몰', 'O-ma', 'SSG닷컴', 'STORE벅스', 'STORYLiNK', 'Tiqui-Taca-BRO', 'Titicaca', 'Woods Coffee', 'duckhip', 'e파인드리빙', 'illy store', 'marketrush', 'ono market', 'spm', '가온인터내셔날', '간결커피로스터스', '감성캠핑 로고스', '고래커피', '골든나인', '그냥 커피', '그라도스커피', '그리니.', '김씨하우스', '꼬미딜', '낫싱 공식스토어', '네이버', '네이쳐플레이스', '뉴웨스트커피', '니드커피', '다다키친', '다얼유 게이밍샵', '다이아몬드그램', '다크브릭스', '댕댕이캠핑', '더써드로스터스', '더캠프빌리지', '덕주방', '드림팩토리샵', '디어다니', '디엘유통', '따봉몰.', '라가커피', '라이빙', '라인코 원두커피', '래빗커피', '레드코코-REDKOCO', '레스트빈', '로스터릭', '로스팅커피원두도매납품쇼핑몰', '로지텍공식스토어', '로지텍정품스토어', '로티몰닷컴', '루비아 커피', '르모네', '리 그', '리빙인저머니', '맘스캠핑', '매드독캠프', '맥스틸 공식스토어', '메이데이31', '모니터 전문 정품 판매점', '모닥불캠핑 거제점', '모르포', '모모스커피', '모사오카', '무드in하우스', '미니코코몰', '미스터송', '미티어소원', '바라던커피', '바이굿즈', '배드머슬러', '백당커피공장', '밴프', '버팔로 캠핑', '베러베스트', '베이니크샵', '보틀스', '볼티움', '브리즈피크', '브리츠 공식몰', '브리츠공식스토어', '블라우풍트', '블랙빈스 커피', '비욘드퍼니싱', '비트 박스', '빈마켓', '빈스메이드', '살림의 힘', '삼대오백 스토어', '삼성JBL온라인스토어', '삼성공식파트너 엠디텍', '삼성공식파트너 엠디텍PC', '삼성공식파트너 오제앤에스', '삼성공식파트너 제이유', '삼성공식파트너사 포디아이', '삼성스마트쇼핑스토어', '삼성인증모니터파트너', '샥즈 코리아', '서원리빙', '설빈', '성정마트', '세네카 커피', '센트팜', '솔루딕캠핑', '송마리커피집', '쇼핑 Pay', '수달리커피', '쉐이크스피어', '스노우커피', '스마트 Inc', '스윗소다', '시골커피', '쏘빗 공식몰', '아이덴티티커피랩', '아이리버 공식대리점 샤후후', '아이리버스토어', '아이언빅', '아임핏', '알맹키즈', '액티브라이프', '어쉐어', '얼리텍', '에디샵 공식판매점', '에센티아 팩토리', '에이디바이크', '오늘새로', '오니지', '오렌지스펙트럼', '올댓픽', '와이드뷰', '와이엘사이언스', '와이제이바스켓', '와이피게이밍기어', '왕도매 아울렛', '워너빈 커피', '원당커피공장', '원두반점', '원두천국', '원스위크라이프', '위즈플래닛', '유로키친', '유리카트', '이너프812', '이든리빙', '이리디아', '이수팩토리로스터즈', '인디에이', '일등대한민국', '일리천국', '일프로커피', '잇츠레저', '제뉴인커피', '제로웨이트', '지포모아', '직구플리즈', '캐주얼캠핑', '캠핑레시피', '캠핑멀티샵', '캠핑토크', '커스텀 커피 마켓', '커피마켓어스', '커피볶는집', '커피창고', '커피포레스트', '케이트마켓', '코스트코이케아', '코시', '코코로운', '코코장수몰', '콩볶는사람들', '콩스콩스', '쿠스포츠', '쿠팡', '쿡샵', '퀘스트빈', '키크론 공식스토어', '킹콩팩토리.', '탑 플레이스', '티에스shop', '티타임커피', '팔공티앤씨', '펀키스', '포랩스커피컴퍼니', '포올', '프라이스킬', '프라이티마켓', '프리플로우', '플랜포티', '플롬아웃도어 울산점', '피쉬앤카', '피에스퍼니싱', '필더컵', '필로비', '하루의 시간', '한성컴퓨터', '헤베커피', '헬로우캠핑', '헬린이상점', '헬킹콩', '홈니크']
    if seller_value in seller_mapping:
        data[f'seller_{seller_value}'] = 1
    elif 'Unknown' in seller_mapping:
        data['seller_Unknown'] = 1
    elif seller_mapping:  # 기본값으로 첫 번째 값 사용
        data[f'seller_{seller_mapping[0]}'] = 1

    # search_keyword 처리
    keyword_value = getattr(request, 'search_keyword', '')
    search_mapping = ['keyword_마우스', 'keyword_모니터', 'keyword_물통', 'keyword_블루투스 이어폰', 'keyword_캠핑 의자', 'keyword_커피 원두', 'keyword_키보드']
    keyword_found = False
    for search_key in search_mapping:
        if keyword_value in search_key or search_key in keyword_value:
            data[f'search_{search_key}'] = 1
            keyword_found = True
            break
    if not keyword_found and search_mapping:
        data[f'search_{search_mapping[0]}'] = 1

    # maker 처리
    maker_value = getattr(request, 'maker', 'Unknown')
    maker_mapping = ['AKT', 'AULA', 'Apple', 'BOB', 'CHERRY', 'COX', 'FLESPORTS', 'KOMAX', 'LG전자', 'MSI', 'QCY', 'QSENN', 'RAZER', 'SPM', 'TOGRAN', 'Unknown', '간결커피로스터스', '날진', '네이처하이크', '뉴웨스트커피', '다얼유', '다크브릭스', '더써드로스터스', '라바짜', '라익미', '라인코', '락앤락', '레드빈', '레토', '레토지엠에스', '로랜텍', '로이체', '로지레스', '로지텍', '로티', '릴팡', '마당발', '마추픽추', '맥스틸', '몽돌', '바라던커피', '바워스앤윌킨스', '백당커피공장', '베러베스트커피', '베이스어스', '벤큐', '보틀스', '브리즈문', '브리츠', '블라우풍트', '블랙빈스', '비니시클', '비에프엘', '삼성전자', '삼지아이티', '소니', '스노우피크', '스케이터', '스타벅스', '스피엘', '아로마빌커피', '아이락스', '아이리버', '아이에이커머스', '알맹', '알파스캔', '앱코', '에센티아팩토리', '에스앤제이스토어', '에이플러스엑스', '엑토', '엠스톤글로벌', '엠엔지이', '엠지텍', '오니지', '오아', '우드인터내셔날', '워너빈로스터리', '유맥스', '익스프레스럭코리아', '인터픽셀', '일디오', '일렉싱크', '일리', '일프로커피컴퍼니', '제뉴인', '제닉스크리에이티브', '젬스트', '주닷', '지오라인', '지클릭커', '지프', '청연엠엔에스', '초이스테크놀로지', '카고컨테이너', '카라신', '카멜', '카즈미', '커세어', '커피디오리진', '커피마켓어스', '커피포레스트', '코뉴', '코베아', '코스트코', '콜맨', '콩볶는사람들', '콩스콩스', '쿠디', '쿠스포츠', '크로스오버존', '키친아트', '키크론', '타파웨어', '토조', '트래딧', '트루버', '티타임', '팔공티앤씨', '포유아이엔씨', '퓨전에프앤씨', '프리플로우', '플랜40', '플랜트로닉스', '필립스', '하이비프리', '한샘', '한성컴퓨터', '헬리녹스']
    if maker_value in maker_mapping:
        data[f'maker_{maker_value}'] = 1
    elif 'Unknown' in maker_mapping:
        data['maker_Unknown'] = 1
    elif maker_mapping:  # 기본값으로 첫 번째 값 사용
        data[f'maker_{maker_mapping[0]}'] = 1

    # naver 카테고리 기본값 설정
    naver_mapping = ['category1_디지털/가전', 'category1_생활/건강', 'category1_스포츠/레저', 'category1_식품', 'category2_모니터', 'category2_음료', 'category2_음향가전', 'category2_주방용품', 'category2_주변기기', 'category2_캠핑', 'category3_nan', 'category3_마우스', 'category3_보관/밀폐용기', 'category3_블루투스셋', 'category3_캠핑가구', 'category3_커피', 'category3_키보드', 'category4_nan', 'category4_무선마우스', 'category4_무선키보드', 'category4_물병', 'category4_블루투스이어폰/이어셋', 'category4_원두/생두', 'category4_유선마우스', 'category4_유선키보드', 'category4_캠핑의자', 'category4_프리젠터']
    # 기본값으로 첫 번째 naver 카테고리 설정
    if naver_mapping:
        data[f'naver_{naver_mapping[0]}'] = 1

    # 정확한 순서로 DataFrame 생성
    feature_order = ['rating', 'review_count', 'purchased_last_month', 'is_prime', 'price_to_category_avg_ratio', 'price_to_keyword_avg_ratio', 'price_x_rating', 'rating_x_review_count', 'price_x_review_count', 'category_디지털/가전 > 모니터', 'category_디지털/가전 > 음향가전 > 블루투스셋 > 블루투스이어폰/이어셋', 'category_디지털/가전 > 주변기기 > 마우스 > 무선마우스', 'category_디지털/가전 > 주변기기 > 마우스 > 유선마우스', 'category_디지털/가전 > 주변기기 > 마우스 > 프리젠터', 'category_디지털/가전 > 주변기기 > 키보드 > 무선키보드', 'category_디지털/가전 > 주변기기 > 키보드 > 유선키보드', 'category_생활/건강 > 주방용품 > 보관/밀폐용기 > 물병', 'category_스포츠/레저 > 캠핑 > 캠핑가구 > 캠핑의자', 'category_식품 > 음료 > 커피 > 원두/생두', 'brand_AULA', 'brand_Apple', 'brand_BOB', 'brand_CHERRY', 'brand_CMF', 'brand_COX', 'brand_DAREU', 'brand_FNR', 'brand_JBL', 'brand_KEEP', 'brand_KOMAX', 'brand_LG그램', 'brand_LG전자', 'brand_MSI', 'brand_NAVEE', 'brand_POLY', 'brand_QCY', 'brand_QSENN', 'brand_RAZER', 'brand_RNRN', 'brand_SPM', 'brand_Unknown', 'brand_갤럭시', 'brand_골든나인', 'brand_꼬미딜', 'brand_날진', 'brand_넘버엔', 'brand_네이처하이크', 'brand_노브랜드', 'brand_노스피크', 'brand_뉴웨스트커피', 'brand_다크브릭스', 'brand_더써드로스터스', 'brand_덕힙', 'brand_델몬트', 'brand_두유니드커피', 'brand_라바짜', 'brand_라익미', 'brand_락셀', 'brand_락앤락', 'brand_람주', 'brand_래빗커피', 'brand_레드빈', 'brand_레드코코', 'brand_레토', 'brand_로랜텍', 'brand_로이체', 'brand_로지텍', 'brand_로지텍G', 'brand_로티캠프', 'brand_루미낙', 'brand_루비아', 'brand_르모네', 'brand_릴팡', 'brand_마운트리버', 'brand_마추픽추', 'brand_매드독캠프', 'brand_맥스틸', 'brand_모모스커피', 'brand_몬테라', 'brand_바라던커피', 'brand_바워스앤윌킨스', 'brand_바이굿즈', 'brand_백당커피공장', 'brand_밴프', 'brand_버팔로', 'brand_베러베스트커피', 'brand_베이니크', 'brand_베이스어스', 'brand_벤큐', 'brand_본플래그', 'brand_볼티움', 'brand_뷰피니티', 'brand_브리즈문', 'brand_브리즈빈', 'brand_브리즈피크', 'brand_브리츠', 'brand_블라우풍트', 'brand_블랙빈스', 'brand_블랜더보틀', 'brand_삼대오백', 'brand_삼성', 'brand_샥즈', 'brand_센트팜', 'brand_소니', 'brand_수달리', 'brand_스노우피크', 'brand_스마트모니터', 'brand_스마트포인터', 'brand_스케이터', 'brand_스타벅스', 'brand_스텐락', 'brand_스피엘', 'brand_쏘빗', 'brand_아우라', 'brand_아이노트', 'brand_아이락스', 'brand_아이리버', 'brand_아임핏', 'brand_알래스카블랙', 'brand_알맹', 'brand_알파스캔', 'brand_앱코', 'brand_어쉐어', 'brand_에센티아팩토리', 'brand_에스메랄다', 'brand_엑스포인터', 'brand_엑토', 'brand_엠스톤', 'brand_엠지텍', 'brand_오니지', 'brand_오디세이', 'brand_오슬로', 'brand_오아', 'brand_와이드뷰', 'brand_울트라기어', 'brand_울트라와이드', 'brand_워너빈', 'brand_원두반점', 'brand_원스위크라이프', 'brand_유맥스', 'brand_인터픽셀', 'brand_일렉싱크', 'brand_일리', 'brand_일프로커피', 'brand_제뉴인', 'brand_제닉스크리에이티브', 'brand_제로웨이트', 'brand_젬스트', 'brand_주닷', 'brand_지오프리', 'brand_지클릭커', 'brand_지프', 'brand_카고컨테이너', 'brand_카나모', 'brand_카디움', 'brand_카멜', 'brand_카즈미', 'brand_캠프빌리지', 'brand_커세어', 'brand_커클랜드', 'brand_커피볶는집', 'brand_커피창고', 'brand_코누', 'brand_코베아', 'brand_코시', 'brand_콜맨', 'brand_콩볶는사람들', 'brand_콩스콩스', 'brand_쿠디', 'brand_쿠스포츠', 'brand_크로스오버', 'brand_키친아트', 'brand_키크론', 'brand_킹콩팩토리', 'brand_타파웨어', 'brand_테라로사', 'brand_토조', 'brand_트루버', 'brand_티버디', 'brand_펄사', 'brand_폴바셋', 'brand_프로쉐이커', 'brand_프리플로우', 'brand_플랜40', 'brand_피스넷', 'brand_필더컵', 'brand_필립스', 'brand_필립스모니터', 'brand_필립스오디오', 'brand_하루의시간', 'brand_한샘', 'brand_한성컴퓨터', 'brand_해커', 'brand_헤베커피', 'brand_헬리녹스', 'seller_2gn', 'seller_BONFLAG', 'seller_Besthall', 'seller_BreezeMoon', 'seller_CHERRY 체리키보드', 'seller_CUCERA', 'seller_DELESHOP', 'seller_FNR', 'seller_HKPHONE', 'seller_Helinox', 'seller_JVR', 'seller_LAKSELV', 'seller_LG전자인증점 DHCNC', 'seller_LG전자인증점 신영플러스', 'seller_LG전자인증점 지오비전', 'seller_MEGACOFFEE', 'seller_N정품 쇼핑몰', 'seller_O-ma', 'seller_SSG닷컴', 'seller_STORE벅스', 'seller_STORYLiNK', 'seller_Tiqui-Taca-BRO', 'seller_Titicaca', 'seller_Woods Coffee', 'seller_duckhip', 'seller_e파인드리빙', 'seller_illy store', 'seller_marketrush', 'seller_ono market', 'seller_spm', 'seller_가온인터내셔날', 'seller_간결커피로스터스', 'seller_감성캠핑 로고스', 'seller_고래커피', 'seller_골든나인', 'seller_그냥 커피', 'seller_그라도스커피', 'seller_그리니.', 'seller_김씨하우스', 'seller_꼬미딜', 'seller_낫싱 공식스토어', 'seller_네이버', 'seller_네이쳐플레이스', 'seller_뉴웨스트커피', 'seller_니드커피', 'seller_다다키친', 'seller_다얼유 게이밍샵', 'seller_다이아몬드그램', 'seller_다크브릭스', 'seller_댕댕이캠핑', 'seller_더써드로스터스', 'seller_더캠프빌리지', 'seller_덕주방', 'seller_드림팩토리샵', 'seller_디어다니', 'seller_디엘유통', 'seller_따봉몰.', 'seller_라가커피', 'seller_라이빙', 'seller_라인코 원두커피', 'seller_래빗커피', 'seller_레드코코-REDKOCO', 'seller_레스트빈', 'seller_로스터릭', 'seller_로스팅커피원두도매납품쇼핑몰', 'seller_로지텍공식스토어', 'seller_로지텍정품스토어', 'seller_로티몰닷컴', 'seller_루비아 커피', 'seller_르모네', 'seller_리 그', 'seller_리빙인저머니', 'seller_맘스캠핑', 'seller_매드독캠프', 'seller_맥스틸 공식스토어', 'seller_메이데이31', 'seller_모니터 전문 정품 판매점', 'seller_모닥불캠핑 거제점', 'seller_모르포', 'seller_모모스커피', 'seller_모사오카', 'seller_무드in하우스', 'seller_미니코코몰', 'seller_미스터송', 'seller_미티어소원', 'seller_바라던커피', 'seller_바이굿즈', 'seller_배드머슬러', 'seller_백당커피공장', 'seller_밴프', 'seller_버팔로 캠핑', 'seller_베러베스트', 'seller_베이니크샵', 'seller_보틀스', 'seller_볼티움', 'seller_브리즈피크', 'seller_브리츠 공식몰', 'seller_브리츠공식스토어', 'seller_블라우풍트', 'seller_블랙빈스 커피', 'seller_비욘드퍼니싱', 'seller_비트 박스', 'seller_빈마켓', 'seller_빈스메이드', 'seller_살림의 힘', 'seller_삼대오백 스토어', 'seller_삼성JBL온라인스토어', 'seller_삼성공식파트너 엠디텍', 'seller_삼성공식파트너 엠디텍PC', 'seller_삼성공식파트너 오제앤에스', 'seller_삼성공식파트너 제이유', 'seller_삼성공식파트너사 포디아이', 'seller_삼성스마트쇼핑스토어', 'seller_삼성인증모니터파트너', 'seller_샥즈 코리아', 'seller_서원리빙', 'seller_설빈', 'seller_성정마트', 'seller_세네카 커피', 'seller_센트팜', 'seller_솔루딕캠핑', 'seller_송마리커피집', 'seller_쇼핑 Pay', 'seller_수달리커피', 'seller_쉐이크스피어', 'seller_스노우커피', 'seller_스마트 Inc', 'seller_스윗소다', 'seller_시골커피', 'seller_쏘빗 공식몰', 'seller_아이덴티티커피랩', 'seller_아이리버 공식대리점 샤후후', 'seller_아이리버스토어', 'seller_아이언빅', 'seller_아임핏', 'seller_알맹키즈', 'seller_액티브라이프', 'seller_어쉐어', 'seller_얼리텍', 'seller_에디샵 공식판매점', 'seller_에센티아 팩토리', 'seller_에이디바이크', 'seller_오늘새로', 'seller_오니지', 'seller_오렌지스펙트럼', 'seller_올댓픽', 'seller_와이드뷰', 'seller_와이엘사이언스', 'seller_와이제이바스켓', 'seller_와이피게이밍기어', 'seller_왕도매 아울렛', 'seller_워너빈 커피', 'seller_원당커피공장', 'seller_원두반점', 'seller_원두천국', 'seller_원스위크라이프', 'seller_위즈플래닛', 'seller_유로키친', 'seller_유리카트', 'seller_이너프812', 'seller_이든리빙', 'seller_이리디아', 'seller_이수팩토리로스터즈', 'seller_인디에이', 'seller_일등대한민국', 'seller_일리천국', 'seller_일프로커피', 'seller_잇츠레저', 'seller_제뉴인커피', 'seller_제로웨이트', 'seller_지포모아', 'seller_직구플리즈', 'seller_캐주얼캠핑', 'seller_캠핑레시피', 'seller_캠핑멀티샵', 'seller_캠핑토크', 'seller_커스텀 커피 마켓', 'seller_커피마켓어스', 'seller_커피볶는집', 'seller_커피창고', 'seller_커피포레스트', 'seller_케이트마켓', 'seller_코스트코이케아', 'seller_코시', 'seller_코코로운', 'seller_코코장수몰', 'seller_콩볶는사람들', 'seller_콩스콩스', 'seller_쿠스포츠', 'seller_쿠팡', 'seller_쿡샵', 'seller_퀘스트빈', 'seller_키크론 공식스토어', 'seller_킹콩팩토리.', 'seller_탑 플레이스', 'seller_티에스shop', 'seller_티타임커피', 'seller_팔공티앤씨', 'seller_펀키스', 'seller_포랩스커피컴퍼니', 'seller_포올', 'seller_프라이스킬', 'seller_프라이티마켓', 'seller_프리플로우', 'seller_플랜포티', 'seller_플롬아웃도어 울산점', 'seller_피쉬앤카', 'seller_피에스퍼니싱', 'seller_필더컵', 'seller_필로비', 'seller_하루의 시간', 'seller_한성컴퓨터', 'seller_헤베커피', 'seller_헬로우캠핑', 'seller_헬린이상점', 'seller_헬킹콩', 'seller_홈니크', 'search_keyword_마우스', 'search_keyword_모니터', 'search_keyword_물통', 'search_keyword_블루투스 이어폰', 'search_keyword_캠핑 의자', 'search_keyword_커피 원두', 'search_keyword_키보드', 'maker_AKT', 'maker_AULA', 'maker_Apple', 'maker_BOB', 'maker_CHERRY', 'maker_COX', 'maker_FLESPORTS', 'maker_KOMAX', 'maker_LG전자', 'maker_MSI', 'maker_QCY', 'maker_QSENN', 'maker_RAZER', 'maker_SPM', 'maker_TOGRAN', 'maker_Unknown', 'maker_간결커피로스터스', 'maker_날진', 'maker_네이처하이크', 'maker_뉴웨스트커피', 'maker_다얼유', 'maker_다크브릭스', 'maker_더써드로스터스', 'maker_라바짜', 'maker_라익미', 'maker_라인코', 'maker_락앤락', 'maker_레드빈', 'maker_레토', 'maker_레토지엠에스', 'maker_로랜텍', 'maker_로이체', 'maker_로지레스', 'maker_로지텍', 'maker_로티', 'maker_릴팡', 'maker_마당발', 'maker_마추픽추', 'maker_맥스틸', 'maker_몽돌', 'maker_바라던커피', 'maker_바워스앤윌킨스', 'maker_백당커피공장', 'maker_베러베스트커피', 'maker_베이스어스', 'maker_벤큐', 'maker_보틀스', 'maker_브리즈문', 'maker_브리츠', 'maker_블라우풍트', 'maker_블랙빈스', 'maker_비니시클', 'maker_비에프엘', 'maker_삼성전자', 'maker_삼지아이티', 'maker_소니', 'maker_스노우피크', 'maker_스케이터', 'maker_스타벅스', 'maker_스피엘', 'maker_아로마빌커피', 'maker_아이락스', 'maker_아이리버', 'maker_아이에이커머스', 'maker_알맹', 'maker_알파스캔', 'maker_앱코', 'maker_에센티아팩토리', 'maker_에스앤제이스토어', 'maker_에이플러스엑스', 'maker_엑토', 'maker_엠스톤글로벌', 'maker_엠엔지이', 'maker_엠지텍', 'maker_오니지', 'maker_오아', 'maker_우드인터내셔날', 'maker_워너빈로스터리', 'maker_유맥스', 'maker_익스프레스럭코리아', 'maker_인터픽셀', 'maker_일디오', 'maker_일렉싱크', 'maker_일리', 'maker_일프로커피컴퍼니', 'maker_제뉴인', 'maker_제닉스크리에이티브', 'maker_젬스트', 'maker_주닷', 'maker_지오라인', 'maker_지클릭커', 'maker_지프', 'maker_청연엠엔에스', 'maker_초이스테크놀로지', 'maker_카고컨테이너', 'maker_카라신', 'maker_카멜', 'maker_카즈미', 'maker_커세어', 'maker_커피디오리진', 'maker_커피마켓어스', 'maker_커피포레스트', 'maker_코뉴', 'maker_코베아', 'maker_코스트코', 'maker_콜맨', 'maker_콩볶는사람들', 'maker_콩스콩스', 'maker_쿠디', 'maker_쿠스포츠', 'maker_크로스오버존', 'maker_키친아트', 'maker_키크론', 'maker_타파웨어', 'maker_토조', 'maker_트래딧', 'maker_트루버', 'maker_티타임', 'maker_팔공티앤씨', 'maker_포유아이엔씨', 'maker_퓨전에프앤씨', 'maker_프리플로우', 'maker_플랜40', 'maker_플랜트로닉스', 'maker_필립스', 'maker_하이비프리', 'maker_한샘', 'maker_한성컴퓨터', 'maker_헬리녹스', 'naver_category1_디지털/가전', 'naver_category1_생활/건강', 'naver_category1_스포츠/레저', 'naver_category1_식품', 'naver_category2_모니터', 'naver_category2_음료', 'naver_category2_음향가전', 'naver_category2_주방용품', 'naver_category2_주변기기', 'naver_category2_캠핑', 'naver_category3_nan', 'naver_category3_마우스', 'naver_category3_보관/밀폐용기', 'naver_category3_블루투스셋', 'naver_category3_캠핑가구', 'naver_category3_커피', 'naver_category3_키보드', 'naver_category4_nan', 'naver_category4_무선마우스', 'naver_category4_무선키보드', 'naver_category4_물병', 'naver_category4_블루투스이어폰/이어셋', 'naver_category4_원두/생두', 'naver_category4_유선마우스', 'naver_category4_유선키보드', 'naver_category4_캠핑의자', 'naver_category4_프리젠터']
    ordered_data = [data.get(feature, 0) for feature in feature_order]

    return pd.DataFrame([ordered_data], columns=feature_order)
